package zym.top.blackobfuscator.gradle;

import org.gradle.api.DefaultTask;
import org.gradle.api.GradleException;
import org.gradle.api.tasks.TaskAction;

import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.OutputStreamWriter;
import java.io.Writer;
import java.nio.file.Files;
import java.util.ArrayList;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Locale;
import java.util.Set;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

public class BlackObfuscatorAutoFilterTask extends DefaultTask {

    private BlackObfuscatorExtension extension;
    private String variantName;
    private File generatedRulesFile;
    private String namespace;
    private static final Pattern PACKAGE_PATTERN = Pattern.compile("(?m)^\\s*package\\s+([A-Za-z_]\\w*(?:\\.[A-Za-z_]\\w*)*)\\s*;?\\s*$");

    @TaskAction
    public void snapshot() {
        if (extension == null || !extension.isEnabled() || !extension.isAutoFilter()) {
            return;
        }
        if (!shouldHandleVariant()) {
            return;
        }
        String autoFilterNamespace = resolveNamespace();
        if (autoFilterNamespace == null || autoFilterNamespace.trim().isEmpty()) {
            throw new GradleException("blackObfuscator.autoFilter requires android.namespace to be configured.");
        }

        Set<String> rules = collectAutoFilterRules(autoFilterNamespace);
        if (rules.isEmpty()) {
            throw new GradleException("No source classes found under namespace " + autoFilterNamespace + " for autoFilter.");
        }

        File outputFile = resolveOutputFile();
        Set<String> mergedRules = readExistingRules(outputFile);
        mergedRules.addAll(rules);

        File parent = outputFile.getParentFile();
        if (parent != null && !parent.isDirectory() && !parent.mkdirs()) {
            throw new GradleException("Failed to create directory " + parent.getAbsolutePath());
        }

        try (Writer writer = new OutputStreamWriter(new FileOutputStream(outputFile), "UTF-8")) {
            writer.write("# Auto generated by BlackObfuscator before Android build\n");
            writer.write("# namespace: " + autoFilterNamespace + "\n");
            for (String rule : mergedRules) {
                writer.write(rule);
                writer.write('\n');
            }
        } catch (IOException e) {
            throw new GradleException("Failed to write auto filter snapshot: " + outputFile.getAbsolutePath(), e);
        }

        getLogger().lifecycle("BlackObfuscator auto filter snapshot: {}", outputFile.getAbsolutePath());
    }

    private File resolveOutputFile() {
        Object rulesFile = extension.getRulesFile();
        if (rulesFile != null) {
            return getProject().file(rulesFile);
        }
        return generatedRulesFile;
    }

    private Set<String> readExistingRules(File file) {
        Set<String> rules = new LinkedHashSet<String>();
        if (file == null || !file.isFile()) {
            return rules;
        }
        try {
            List<String> lines = Files.readAllLines(file.toPath());
            for (String line : lines) {
                String rule = line.trim();
                if (rule.isEmpty() || rule.startsWith("#")) {
                    continue;
                }
                rules.add(rule);
            }
        } catch (IOException e) {
            throw new GradleException("Failed to read rules file: " + file.getAbsolutePath(), e);
        }
        return rules;
    }

    private Set<String> collectAutoFilterRules(String autoFilterNamespace) {
        File srcDir = new File(getProject().getProjectDir(), "src");
        Set<String> rules = new LinkedHashSet<String>();
        List<File> sources = new ArrayList<File>();
        collectSourceFiles(srcDir, sources);

        for (File source : sources) {
            String declaredPackage = readDeclaredPackage(source);
            if (declaredPackage == null || !isNamespaceMatch(declaredPackage, autoFilterNamespace)) {
                continue;
            }

            String simpleName = source.getName();
            int dot = simpleName.lastIndexOf('.');
            if (dot > 0) {
                simpleName = simpleName.substring(0, dot);
            }
            if (!simpleName.isEmpty()) {
                rules.add(declaredPackage + "." + simpleName);
            }
        }
        return rules;
    }

    private void collectSourceFiles(File dir, List<File> result) {
        if (dir == null || !dir.isDirectory()) {
            return;
        }
        File[] files = dir.listFiles();
        if (files == null) {
            return;
        }
        for (File file : files) {
            if (file.isDirectory()) {
                if ("build".equals(file.getName())) {
                    continue;
                }
                collectSourceFiles(file, result);
            } else if (isSourceFile(file)) {
                result.add(file);
            }
        }
    }

    private boolean isSourceFile(File file) {
        String name = file.getName().toLowerCase(Locale.ROOT);
        return name.endsWith(".java") || name.endsWith(".kt");
    }

    private String readDeclaredPackage(File source) {
        try {
            String content = new String(Files.readAllBytes(source.toPath()), "UTF-8");
            Matcher matcher = PACKAGE_PATTERN.matcher(content);
            if (matcher.find()) {
                return matcher.group(1);
            }
        } catch (IOException ignored) {
        }
        return null;
    }

    private boolean isNamespaceMatch(String packageName, String autoFilterNamespace) {
        return packageName.equals(autoFilterNamespace) || packageName.startsWith(autoFilterNamespace + ".");
    }

    private String resolveNamespace() {
        if (namespace != null && !namespace.trim().isEmpty()) {
            return namespace.trim();
        }
        return readManifestPackage();
    }

    private String readManifestPackage() {
        File manifest = new File(getProject().getProjectDir(), "src/main/AndroidManifest.xml");
        String packageName = readManifestPackage(manifest);
        if (packageName != null) {
            return packageName;
        }

        File mainSourceDir = new File(getProject().getProjectDir(), "src/main");
        File[] manifests = mainSourceDir.listFiles((dir, name) ->
                name.startsWith("AndroidManifest") && name.endsWith(".xml"));
        if (manifests == null) {
            return null;
        }
        for (File candidate : manifests) {
            packageName = readManifestPackage(candidate);
            if (packageName != null) {
                return packageName;
            }
        }
        return null;
    }

    private String readManifestPackage(File manifest) {
        if (manifest == null || !manifest.isFile()) {
            return null;
        }
        try {
            String content = new String(Files.readAllBytes(manifest.toPath()), "UTF-8");
            Matcher matcher = Pattern.compile("package\\s*=\\s*\"([^\"]+)\"").matcher(content);
            if (matcher.find()) {
                return matcher.group(1).trim();
            }
        } catch (IOException ignored) {
        }
        return null;
    }

    private boolean shouldHandleVariant() {
        List<String> variants = extension.getVariants();
        if (variants == null || variants.isEmpty()) {
            return true;
        }
        for (String candidate : variants) {
            if (variantName.equalsIgnoreCase(candidate)) {
                return true;
            }
        }
        return false;
    }

    public void setExtension(BlackObfuscatorExtension extension) {
        this.extension = extension;
    }

    public void setVariantName(String variantName) {
        this.variantName = variantName;
    }

    public void setGeneratedRulesFile(File generatedRulesFile) {
        this.generatedRulesFile = generatedRulesFile;
    }

    public void setNamespace(String namespace) {
        this.namespace = namespace;
    }
}
